/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-11 07:47:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1573457100071L));
    _jspx_dependants.put("jar:file:/C:/spring_workspace/dstayProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"description\" content=\"Kimi is a curated foods and beverages artisans.\">\r\n");
      out.write("    <meta name=\"author\" content=\"Johnson Chandra, Allysa Prabandani, Philipus Herlambang, Maya Editorial\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("    <meta name=\"mobile-web-app-capable\" content=\"yes\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("    <meta name=\"title\" content=\"Back to Kimi\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Language\" content=\"en-id\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- open graph metadata facebook, slack, whatsapp line -->\r\n");
      out.write("    <meta property=\"fb:app_id\" content=\"150112802189143\"/>\r\n");
      out.write("    <meta property=\"og:locale\" content=\"en_US\" />\r\n");
      out.write("    <meta property=\"og:title\" content=\"Back to Kimi\" />\r\n");
      out.write("    <meta property='og:site_name' content='Kimi | Curated Foods and Beverages' />\r\n");
      out.write("    <meta property=\"og:url\" content=\"http://kimistatic.s3-website-ap-southeast-1.amazonaws.com/\" />\r\n");
      out.write("    <meta property=\"og:description\" content=\"Kimi is a curated foods and beverages artisans.\" />\r\n");
      out.write("    <meta property='og:image' content=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/apple-touch-icon.png\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- open graph metadata twitter -->\r\n");
      out.write("    <meta name=\"twitter:title\" content=\"Back to Kimi\">\r\n");
      out.write("    <meta name=\"twitter:url\" content=\"http://www.backtokimi.com\">\r\n");
      out.write("    <meta name=\"twitter:description\" content=\"Kimi is a curated foods and beverages artisans.\">\r\n");
      out.write("    <meta name=\"twitter:image\" content=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/apple-touch-icon.png\">\r\n");
      out.write("    <meta name=\"twitter:site\" content=\"@backtokimi\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/favicon.ico\">\r\n");
      out.write("    <link rel=\"apple-touch-icon\" href=\"https://s3-ap-southeast-1.amazonaws.com/kimistatic/images/apple-touch-icon.png\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/kimi.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>loginForm</title>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://ricostacruz.com/jquery.transit/jquery.transit.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Boot Strap -->\r\n");
      out.write("    <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template css-->\r\n");
      out.write("    <link href=\"resources/css/kimi.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom css -->\r\n");
      out.write("    <link href=\"resources/css/logo-top.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/top-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/mainBanner.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom JavaScript-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/mobile-menu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/mainBanner.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        background:rgb(245, 245, 245);\r\n");
      out.write("    }\r\n");
      out.write("    html {\r\n");
      out.write("        padding-bottom: 50px;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write(".modal {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("@media screen and (min-width: 768px) { \r\n");
      out.write("        .modal:before {\r\n");
      out.write("                display: inline-block;\r\n");
      out.write("                vertical-align: middle;\r\n");
      out.write("                content: \" \";\r\n");
      out.write("                height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write(".modal-dialog {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* 테스트용 CSS */\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"fixedArea\">\r\n");
      out.write("    <div class=\"topFixedDiv\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"logo-top\">\r\n");
      out.write("        <div class=\"topLeft\">\r\n");
      out.write("                <a href=\"\"><img src=\"resources/images/logo.png\" width=100px></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"topMiddle\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"검색어를 입력해주세요.\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"topRight\">\r\n");
      out.write("             <!-- pc버전 -->\r\n");
      out.write("            <div class=\"size-pc\">\r\n");
      out.write("                <a href=\"\">로그인</a>\r\n");
      out.write("                <a href=\"\">마이페이지</a>\r\n");
      out.write("                <a href=\"\">장바구니</a>\r\n");
      out.write("                <a href=\"\">고객센터</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 모바일버전 (화면작은) -->\r\n");
      out.write("            <div class=\"size-mobile\">\r\n");
      out.write("                <img class=\"test\" src=\"resources/images/listTest.png\" onclick=\"mobileOpenMenu();\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 아이콘 누르면 나타날 메뉴리스트 -->\r\n");
      out.write("                <div class=\"icon-menuList\">\r\n");
      out.write("                    <div class=\"menuList-title\">차종환 님</div>\r\n");
      out.write("                    <div id=\"menuList-select\"></div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">로그인</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">마이페이지</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">장바구니</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">고객센터</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon-menuList-leave\" onclick=\"mobileCloseMenu();\">메뉴바 닫기</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu-div\">\r\n");
      out.write("            <div class=\"menu-line\">메뉴목록</div>\r\n");
      out.write("            <div class=\"menu-line\">베스트목록</div>\r\n");
      out.write("            <div class=\"menu-line\">신상품</div>\r\n");
      out.write("            <div class=\"menu-line\">할인품목</div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"kimi-container\">\r\n");
      out.write("        <!--breadcrumb start-->\r\n");
      out.write("        <ol class=\"breadcrumb hidden-xs\">\r\n");
      out.write("            <li><a href=\"index.html\">Home</a></li>\r\n");
      out.write("            <li class=\"active\">로그인</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("<!--         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12 col-md-offset-12\"> -->\r\n");
      out.write("        <div class=\"row\" >\r\n");
      out.write("                    <div class=\"box-bg-white col-md-6 col-xs-6 form-medium-padding\">\r\n");
      out.write("                        <h3 class=\"text-center text-gray-1\">디스테이 로그인</h3>\r\n");
      out.write("                        <!-- <div class=\"clearfix maya-tiny-padding\"></div> -->\r\n");
      out.write("                        \r\n");
      out.write("                        <div class=\"clearfix maya-small-padding\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"이메일/전화번호\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"password\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"비밀번호\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                             <div class=\"checkbox\" style=\"float:left;\">\r\n");
      out.write("                                <label>\r\n");
      out.write("                                    <input type=\"checkbox\"> <span class=\"text-gray-2 helvetica-12\">아이디 기억하기</span>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div> \r\n");
      out.write("                            <!--비밀번호찾기  -->\r\n");
      out.write("                                                        <div class=\"checkbox\" align=\"right\" style=\"float:right\">\r\n");
      out.write("                                                        <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                                <label>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-outline-primary\" data-toggle=\"modal\" data-target=\"#exampleModal\" data-whatever=\"@mdo\"><span class=\"text-gray-2 helvetica-12\">비밀번호찾기</span></button>\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!--일시적으로   -->\r\n");
      out.write("                           <!--  <button type=\"submit\" class=\"btn btn-block button-green-free btn-lg\">로그인</button> -->\r\n");
      out.write("                           <button type=\"button\" class=\"btn btn-block button-green-free btn-lg\" onclick=\"location.href='emailVerify.me';\">로그인</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                        <p class=\"text-center\">아직 회원이 아니신가요&nbsp;<a href=\"registerForm.me\" class=\"text-secondary\">&nbsp;회원가입</a></p>\r\n");
      out.write("                       <!--  <p class=\"text-center\">비회원으로 주문하셨나요&nbsp;<a href=\"nonMemOrderViewForm.me\" class=\"text-secondary\">&nbsp;비회원주문조회</a></p> -->\r\n");
      out.write("                        <!-- <div class=\"clearfix maya-small-padding\"></div> -->\r\n");
      out.write("                        <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <button class=\"button-connect-google btn-block\"><i class=\"fa fa-google\" style=\"font-size:24px;margin-right:18px\"></i>구글로 로그인하기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                                                <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <button class=\"button-connect-naver btn-block\"><img src=\"resources/images/naver_icon_img.PNG\">네이버로 로그인하기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("                            <div class=\"col-md-12\">\r\n");
      out.write("                                <button class=\"button-connect-kakao btn-block\"><img src=\"resources/images/kakaolink_btn_small.png\">카카오로 로그인하기</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- 비밀번호 모달창 -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\" align=\"left\" style=\"font-size:12px\">입력하신 이메일 / 휴대폰번호로 임시비밀번호를 발송해 드립니다</h5>\r\n");
      out.write("        <!-- <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"> -->\r\n");
      out.write("         <!--  <span aria-hidden=\"true\">&times;</span> -->\r\n");
      out.write("       <!--  </button> -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        <form>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <label for=\"recipient-name\" class=\"col-form-label\" style=\"float:left\">이메일 / 휴대폰번호</label>\r\n");
      out.write("            <input type=\"email\" class=\"form-control\" id=\"recipient-name\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-outline-primary\">비밀번호 발송</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"box-bg-white col-md-6 col-xs-6 form-medium-padding\">\r\n");
      out.write("                        <h3 class=\"text-center text-gray-1\">비회원 주문 조회</h3>\r\n");
      out.write("                        <div class=\"clearfix maya-small-padding\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <form>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"business_name\" placeholder=\"이름\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"tagline\" placeholder=\"주문 번호\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("<!--                             <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"email\" class=\"form-control\" id=\"bank_account\" placeholder=\"이메일\">\r\n");
      out.write("                            </div> -->\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"tel\" class=\"form-control\" id=\"account_number\" placeholder=\"휴대폰 번호\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("<!--                             <div class=\"form-group\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" id=\"bank_account_name\" placeholder=\"Bank Account Name\">\r\n");
      out.write("                            </div> -->\r\n");
      out.write("\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-block button-green-free btn-lg\">조회 하기</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("                        <p class=\"text-center\">회원이 아니신가요 &nbsp;<a href=\"registerForm.me\" class=\"text-secondary\">&nbsp;회원가입</a></p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                \t\r\n");
      out.write("                </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><!-- /.container -->\r\n");
      out.write("\r\n");
      out.write("<!--include footer-->\r\n");
      out.write("<div class=\"include-footer\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core JavaScript\r\n");
      out.write("================================================== -->\r\n");
      out.write("<!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("<script src=\"resources/js/jquery.min.js\"></script>\r\n");
      out.write("<script>window.jQuery || document.write('<script src=\"../../assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("<script src=\"resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!--kimi basic js-->\r\n");
      out.write("<script src=\"resources/js/kimi.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
