/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-11 07:44:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1573457100071L));
    _jspx_dependants.put("jar:file:/C:/spring_workspace/dstayProject/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>index</title>\r\n");
      out.write("</head>\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://ricostacruz.com/jquery.transit/jquery.transit.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Boot Strap -->\r\n");
      out.write("    <link href=\"resources/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template css-->\r\n");
      out.write("    <link href=\"resources/css/kimi.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom css -->\r\n");
      out.write("    <link href=\"resources/css/logo-top.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/top-menu.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"resources/css/mainBanner.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom JavaScript-->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/mobile-menu.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"resources/js/mainBanner.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("    html, body {\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        background:rgb(245, 245, 245);\r\n");
      out.write("    }\r\n");
      out.write("    html {\r\n");
      out.write("        padding-bottom: 50px;\r\n");
      out.write("    min-height: 100%;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    -moz-box-sizing: border-box;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    /* 테스트용 CSS */\r\n");
      out.write("    </style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"fixedArea\">\r\n");
      out.write("    <div class=\"topFixedDiv\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"logo-top\">\r\n");
      out.write("        <div class=\"topLeft\">\r\n");
      out.write("                <a href=\"\"><img src=\"resources/images/logo.png\" width=100px></a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"topMiddle\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"검색어를 입력해주세요.\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"topRight\">\r\n");
      out.write("             <!-- pc버전 -->\r\n");
      out.write("            <div class=\"size-pc\">\r\n");
      out.write("                <a href=\"loginForm.do\">로그인</a>\r\n");
      out.write("                <a href=\"\">마이페이지</a>\r\n");
      out.write("                <a href=\"\">장바구니</a>\r\n");
      out.write("                <a href=\"\">고객센터</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- 모바일버전 (화면작은) -->\r\n");
      out.write("            <div class=\"size-mobile\">\r\n");
      out.write("                <img class=\"test\" src=\"resources/images/listTest.png\" onclick=\"mobileOpenMenu();\">\r\n");
      out.write("\r\n");
      out.write("                <!-- 아이콘 누르면 나타날 메뉴리스트 -->\r\n");
      out.write("                <div class=\"icon-menuList\">\r\n");
      out.write("                    <div class=\"menuList-title\">차종환 님</div>\r\n");
      out.write("                    <div id=\"menuList-select\"></div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">로그인</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">마이페이지</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">장바구니</div>\r\n");
      out.write("                    <div><img src=\"resources/images/menusmallicon.png\">고객센터</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"icon-menuList-leave\" onclick=\"mobileCloseMenu();\">메뉴바 닫기</div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"menu-div\">\r\n");
      out.write("            <div class=\"menu-line\">메뉴목록</div>\r\n");
      out.write("            <div class=\"menu-line\">베스트목록</div>\r\n");
      out.write("            <div class=\"menu-line\">신상품</div>\r\n");
      out.write("            <div class=\"menu-line\">할인품목</div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Banner 부분 -->\r\n");
      out.write("    <div class=\"mainBanner\">\r\n");
      out.write("        <div class=\"mainBanner-img banner-pc\">\r\n");
      out.write("            <img src=\"resources/images/banner1.png\">\r\n");
      out.write("            <img src=\"resources/images/banner2.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"mainBanner-img banner-mobile\">\r\n");
      out.write("            <img src=\"resources/images/banner1.png\">\r\n");
      out.write("            <img src=\"resources/images/banner2.png\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"col-xs-1 text-center banner-btn\">안녕</div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- BootStrap Template -->\r\n");
      out.write("    <div class=\"clearfix maya-tiny-padding\"></div>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("    \r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <h2 class=\"default-userProductList-InfoBar-title text-center\"><i class=\"fa fa-heart-o\" aria-hidden=\"true\"></i> This Week Favoourites</h2>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"col-sm-6 col-md-4\" data-behavior=\"sample_code\">\r\n");
      out.write("                    <a href=\"productDetail.html\" class=\"thumbnail_item thumbnail less-padding less-margin\">\r\n");
      out.write("                        <img src=\"resources/images/nurung.jpg\" alt=\"risotto lemon\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"caption box\">\r\n");
      out.write("                        <h3>현미 누룽지 5종 세트</h3>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-8 col-xs-6\">\r\n");
      out.write("                                <p class=\"default-userProductList-CardList-price\">25,000원</p>\r\n");
      out.write("                                <span class=\"min-order\">여기에 네모낳게 div 들어감</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("    \r\n");
      out.write("                            <div class=\"col-sm-4 col-xs-6\">\r\n");
      out.write("                                <button onclick=\"location.href='shoppingCart.html'\" class=\"btn default-userProductList-CardList-button pull-right\" role=\"button\">Add to Cart</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("    \r\n");
      out.write("                <div class=\"col-sm-6 col-md-4\" data-behavior=\"sample_code\">\r\n");
      out.write("                    <a href=\"productDetail.html\" class=\"thumbnail_item thumbnail less-padding less-margin\">\r\n");
      out.write("                        <img src=\"resources/images/nurung2.jpg\" alt=\"risotto lemon\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"caption box\">\r\n");
      out.write("                        <h3>현미 누룽지 5종 세트</h3>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-8 col-xs-6\">\r\n");
      out.write("                                <p class=\"default-userProductList-CardList-price\">Rp 45.000 / pcs</p>\r\n");
      out.write("                                <span class=\"min-order\">10 pcs min order</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("    \r\n");
      out.write("                            <div class=\"col-sm-4 col-xs-6\">\r\n");
      out.write("                                <button onclick=\"location.href='shoppingCart.html'\" class=\"btn default-userProductList-CardList-button pull-right\" role=\"button\">Add to Cart</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4\" data-behavior=\"sample_code\">\r\n");
      out.write("                    <a href=\"productDetail.html\" class=\"thumbnail_item thumbnail less-padding less-margin\">\r\n");
      out.write("                        <img src=\"resources/images/nurung2.jpg\" alt=\"risotto lemon\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"caption box\">\r\n");
      out.write("                        <h3>현미 누룽지 5종 세트</h3>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-8 col-xs-6\">\r\n");
      out.write("                                <p class=\"default-userProductList-CardList-price\">Rp 45.000 / pcs</p>\r\n");
      out.write("                                <span class=\"min-order\">10 pcs min order</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("    \r\n");
      out.write("                            <div class=\"col-sm-4 col-xs-6\">\r\n");
      out.write("                                <button onclick=\"location.href='shoppingCart.html'\" class=\"btn default-userProductList-CardList-button pull-right\" role=\"button\">Add to Cart</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-sm-6 col-md-4\" data-behavior=\"sample_code\">\r\n");
      out.write("                    <a href=\"productDetail.html\" class=\"thumbnail_item thumbnail less-padding less-margin\">\r\n");
      out.write("                        <img src=\"resources/images/nurung2.jpg\" alt=\"risotto lemon\">\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"caption box\">\r\n");
      out.write("                        <h3>현미 누룽지 5종 세트</h3>\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("                            <div class=\"col-sm-8 col-xs-6\">\r\n");
      out.write("                                <p class=\"default-userProductList-CardList-price\">Rp 45.000 / pcs</p>\r\n");
      out.write("                                <span class=\"min-order\">10 pcs min order</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("    \r\n");
      out.write("                            <div class=\"col-sm-4 col-xs-6\">\r\n");
      out.write("                                <button onclick=\"location.href='shoppingCart.html'\" class=\"btn default-userProductList-CardList-button pull-right\" role=\"button\">Add to Cart</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- BootStrap Template END-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function(){\r\n");
      out.write("    // 페이지 로드될 때 Banner display 풀어주는 부분입니다.\r\n");
      out.write("        var $imgPc = $(\".banner-pc img\");\r\n");
      out.write("        var $imgMobile = $(\".banner-mobile img\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $imgPc.eq(0).css(\"display\",\"inherit\");\r\n");
      out.write("        $imgMobile.eq(0).css(\"display\",\"inherit\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
